#!/bin/bash
#Probably still a WIP; gradually filling in bits as I go

############
#  backup  #
############

#Backup existing directories
BACKUPDIR=~/"$(date +"%d-%m-%Y_%H%M%S")"_dotfiles_backup

if [ -d "$BACKUPDIR" ]; then
    echo "The directory "$BACKUPDIR" already exists."
    echo "Aborting..."
    return 1 2>/dev/null
    exit 1
fi

echo "Creating backup directory..."
mkdir "$BACKUPDIR"

if [ ! -d "$BACKUPDIR" ]; then
    echo "The directory "$BACKUPDIR" could not be created succesfully."
    echo "Aborting..."
    return 1 2>/dev/null
    exit 1
fi

#Move files into backup directory if they exist
echo "Moving existing configuration files..."
[ -d ~/.config ] && mv ~/.config "$BACKUPDIR"
[ -d ~/.Xresources ] && mv ~/.Xresources "$BACKUPDIR"
[ -d ~/.oh-my-zsh ] && mv ~/.oh-my-zsh "$BACKUPDIR"
[ -f ~/.p10k.zsh ] && mv ~/.p10k.zsh "$BACKUPDIR"
[ -f ~/.tmux.conf ] && mv ~/.tmux.conf "$BACKUPDIR"
[ -f ~/.zshrc ] && mv ~/.zshrc "$BACKUPDIR"
[ -d ~/.spicetify_data ] && mv ~/.spicetify_data "$BACKUPDIR"

mkdir ~/.config

##########
#  brew  #
##########

#install brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

#tap casks
brew tap homebrew/cask-fonts #nerdfont
brew tap colinstein/imgcat
brew tap zegervdv/zathura

#run update before installing packages
brew update

#Applications
brew install zsh
brew install python
brew install node
brew install tmux
brew install neovim
brew install skhd
brew install yabai
brew install neovim
brew install neofetch
brew install gotop
brew install imgcat
brew install --cask firefox
brew install --cask spotify

#Nerd fonts
brew install --cask font-meslo-nerd-font
brew install --cask font-noto-nerd-font
brew install --cask font-inconsolata-nerd-font
brew install --cask font-jetbrains-mono

#Zathura
brew install zathura
brew install zathura-pdf-poppler
mkdir -p $(brew --prefix zathura)/lib/zathura
ln -s $(brew --prefix zathura-pdf-poppler)/libpdf-poppler.dylib $(brew --prefix zathura)/lib/zathura/libpdf-poppler.dylib

#run one final brew upgrade
brew upgrade
#remove unused dependencies
brew autoremove

echo "Brew installations complete..."

############
#  python  #
############

echo "Installing python..."
#speficially use python2/python3 -m pip just to be safe
python3 -m pip install pynvim 
python2 -m pip install pynvim 2>/dev/null

###########
#  other  #
###########

#if git isn't installed this will prompt an installation window
git --version > /dev/null

#ohmyzsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

#fast-syntax-highlighting
git clone https://github.com/zdharma/fast-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting

#p10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

#yabai scripting addon
sudo yabai --install-sa

############################
#  copy files and symlink  #
############################

#Copy config files to ~/.config
echo "Copying new config files..."
SOURCEDIR=$(dirname "$0")
cp "SOURCEDIR/*" ~/.config


#Symlink binaries into ~/.local/bin
echo "Linking binaries..."
[ ! -d ~/.local/bin ] && mkdir -p ~/.local/bin
ln -s ~/.config/bunt/build-new-theme ~/.local/bin/bunt
ln -s ~/.config/skhd/switcher ~/.local/bin/skhs


#Create symlinks so all the information is actually contained within ~/.config/
echo "Creating symlinks..."
ln -s ~/.config/xresources/.Xresources ~/.Xresources
ln -s ~/.config/.oh-my-zsh ~/.oh-my-zsh
ln -s ~/.config/p10k/.p10k.zsh ~/.p10k.zsh
ln -s ~/.config/zsh/.zshrc ~/.zshrc
ln -s ~/.config/spicetify_data ~/spicetify_data

#Symlink active vim theme (wal by default)
ln -s ~/.config/nvim/config/themes/pywal.vim ~/.config/nvim/active_theme.vim

##################
#  post install  #
##################

#make zsh default shell
chsh -s $(which zsh)

#apply fast syntax theme
fast-theme ~/.config/fast-syntax-highlighting/syntax-colors.ini

#start yabai service
brew services start yabai

#set up spicetify
#custom apps aren't included in the brew build i think?
#thus clone the repo, move folders and delete tmp
[ -d ~/.config/tmp ] && mkdir ~/.config/tmp
git clone https://github.com/khanhas/spicetify-cli.git ~./config/tmp
mv ~/.config/tmp/spicetify-cli/CustomApps/* ~/.config/spicetify_data/CustomApps
rm -rf ~/.config/tmp
spicetify backup apply enable-devtool


echo "Manual adjustments might be required:"
echo "Install the pywal firefox extension"
echo "Set the iterm font"
