#!/bin/bash
#Probably still a WIP; gradually filling in bits as I go

############
#  backup  #
############

#Backup existing directories
BACKUPDIR=~/"$(date +"%d-%m-%Y_%H%M%S")"_dotfiles_backup

if [ -d "$BACKUPDIR" ]; then
    echo "The directory "$BACKUPDIR" already exists." echo "Aborting..."
    return 1 2>/dev/null
    exit 1
fi

echo "Creating backup directory..."
mkdir "$BACKUPDIR"

if [ ! -d "$BACKUPDIR" ]; then
    echo "The directory "$BACKUPDIR" could not be created succesfully."
    echo "Aborting..."
    return 1 2>/dev/null
    exit 1
fi

#Move files into backup directory if they exist
echo "Moving existing configuration files..."
[ -d ~/.config ] && mv ~/.config "$BACKUPDIR"
[ -d ~/.Xresources ] && mv ~/.Xresources "$BACKUPDIR"
[ -d ~/.oh-my-zsh ] && mv ~/.oh-my-zsh "$BACKUPDIR"
[ -f ~/.p10k.zsh ] && mv ~/.p10k.zsh "$BACKUPDIR"
[ -f ~/.tmux.conf ] && mv ~/.tmux.conf "$BACKUPDIR"
[ -f ~/.zshrc ] && mv ~/.zshrc "$BACKUPDIR"

mkdir ~/.config

##########
#  brew  #
##########

#install brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

#tap casks
brew tap homebrew/cask-fonts #nerdfont
brew install eddieantonio/eddieantonio/imgcat
brew tap zegervdv/zathura

#run update before installing packages
brew update

#set up rtx and languages
brew install rtx
echo 'eval "$(~/bin/rtx activate zsh)"' >> ~/.zshrc
source ~/.zshrc

rtx use -g python@latest
rtx use -g node@latest

#Applications
brew install zsh
brew install tmux
brew install neovim
brew install skhd
brew install yabai
brew install neofetch
brew install gotop
brew install imgcat
brew install --cask firefox
brew install --cask spotify
brew install --cask discord
brew install khanhas/tap/spicetify-cli #might be oudated?
brew install xdotool
brew install dbus && brew reinstall dbus
brew install fzf
brew install pstree
brew install --cask ubersicht
brew install ctags
brew install ripgrep
brew install exa
brew install bat
brew install nushell

#Nerd fonts
brew install --cask font-meslo-nerd-font
brew install --cask font-noto-nerd-font
brew install --cask font-inconsolata-nerd-font
brew install --cask font-jetbrains-mono

#Zathura
sudo sed -i '' 's/>EXTERNAL</>DBUS_COOKIE_SHA1</g' /usr/local/opt/dbus/share/dbus-1/session.conf
brew services start dbus
brew install girara
brew install zathura --with-synctex
brew install zathura-pdf-poppler
mkdir -p $(brew --prefix zathura)/lib/zathura
ln -s $(brew --prefix zathura-pdf-poppler)/libpdf-poppler.dylib $(brew --prefix zathura)/lib/zathura/libpdf-poppler.dylib

#run one final brew upgrade
brew upgrade
#remove unused dependencies
brew autoremove

echo "Brew installations complete..."

##########
#  rust  #
##########

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
echo "Rust toolchain installed..."

cargo install cargo-update
cargo install starship


############
#  python  #
############

echo "Installing python..."
python -m pip install pynvim 
python -m pip install neovim-remote
python -m pip install rope
python -m pip install spotify-cli

##########
#  node  #
##########

npm install -g neovim


###########
#  other  #
###########

#if git isn't installed this will prompt an installation window
#though if it isn't installed the macos version is probably ancient enough to break other things
git --version > /dev/null

#ohmyzsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

#fast-syntax-highlighting
git clone https://github.com/zdharma/fast-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting

#p10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

#yabai scripting addon
sudo yabai --install-sa

#better discord
sudo chown -R "$USER":staff /Applications/Discord.app
git clone https://github.com/BetterDiscord/BetterDiscord.git
cd BetterDiscord && npm install
npm run build
npm run inject
cd .. & rm -r BetterDiscord

#simple-bar
git clone https://github.com/Jean-Tinland/simple-bar $HOME/Library/Application\ Support/Übersicht/widgets/simple-bar

############################
#  copy files and symlink  #
############################

#Copy config files to ~/.config
echo "Copying new config files..."
SOURCEDIR=$(dirname "$0")
cp "SOURCEDIR/*" ~/.config


#Symlink binaries into ~/.local/bin
echo "Linking binaries..."
[ ! -d ~/.local/bin ] && mkdir -p ~/.local/bin
ln -s ~/.config/bunt/build-new-theme ~/.local/bin/bunt
ln -s ~/.config/skhd/switcher ~/.local/bin/skhs


#Create symlinks so all the information is actually contained within ~/.config/
echo "Creating symlinks..."
ln -s ~/.config/xresources/.Xresources ~/.Xresources
ln -s ~/.config/.oh-my-zsh ~/.oh-my-zsh
ln -s ~/.config/p10k/.p10k.zsh ~/.p10k.zsh
ln -s ~/.config/zsh/.zshrc ~/.zshrc

#Symlink active vim theme (wal by default)
ln -sfn ~/.config/nvim/config/themes/pywal.vim ~/.config/nvim/active_theme.vim

##################
#  post install  #
##################

#make zsh default shell
chsh -s $(which zsh)

#symlink python3 if not already exists
#required for jabrefExtension
[ ! -f /usr/bin/python3 ] && ln -s /usr/local/bin/python3 /usr/bin/python3

#apply fast syntax theme
fast-theme ~/.config/fast-syntax-highlighting/syntax-colors.ini

#start yabai service
brew services start yabai

#set up zathura pywal support
chmod +x ~/.config/zathura/install.sh
~/.config/zathura/install.sh

#set up pywal-discord
git clone https://github.com/FilipLitwora/pywal-discord.git ~/.config/
chmod +x ~/.config/pywal-discord/install
~/.config/pywal-discord/install
~/.config/bunt/pywal-discord-fix


#set up spicetify
spicetify update #brew version is probably going to be outdated!

#custom apps aren't included in the brew build i think?
#thus clone the repo, move folders and delete tmp
[ -d ~/.config/tmp ] && mkdir ~/.config/tmp
git clone https://github.com/khanhas/spicetify-cli.git ~./config/tmp
mv ~/.config/tmp/spicetify-cli/CustomApps/* ~/.config/spicetify/CustomApps
rm -rf ~/.config/tmp
spicetify backup apply enable-devtool

#set up starship
echo 'eval "$(starship init zsh)"' >> ~/.config/zsh/.zshrc



echo "Manual adjustments might be required:"
echo "Install the pywal firefox extension"
echo "Set the iterm font"
