#!/bin/bash
DIR=$HOME/.config/bunt
GET_WALLPAPER=true



# remove manually wal cache
echo -n "Removing previous wal cache..."
rm -rf "$HOME/.cache/wal/*_config_bunt_wallpaper_*"
echo " ✔️"

if [ ! $# -eq 0 ]; then
    if [ ! -f "$1" ]; then
        echo "$1 is not a file! Aborting..."
        return 1 2>/dev/null
        exit 1
    fi

    cp -v "$1" "$DIR/wallpaper"

    wal -i $DIR/wallpaper --backend haishoku

    imgcat --height 10 $DIR/wallpaper

else
    while [ "$GET_WALLPAPER" == "true" ]
    do
        # fetch random wallpaper from unsplash
        echo -n "Fetching a random wallpaper..."
        wget -O $DIR/wallpaper https://source.unsplash.com/random/1920x1080 > /dev/null 2>&1
        echo " ✔️"

        # generate colors palette, skip setting wallpaper
        echo "Generating colours..."
        wal -i $DIR/wallpaper --backend haishoku

        imgcat --height 10 $DIR/wallpaper

        while true; do
            echo "Are you happy with this theme?"
            read -p "" yn
            case $yn in
                [Yy]* ) GET_WALLPAPER=false; break;;
                [Nn]* ) GET_WALLPAPER=true; break;;
                * ) echo "Please answer yes or no.";;
            esac
        done
    done
fi

#clear neofetch cache
neofetch --clean

#apply to discord
#run pywal-discord-fix if this isn't working
echo -n "Applying new theme to discord..."
pywal-discord
echo " ✔️"

#apply to spotify
echo "Applying new theme to spotify..."
if ! pgrep "Spotify" 1>/dev/null; then
    spicetify apply -n
else
    spicetify apply
fi

#quit xquartz after applying spotify theme
echo -n "Quitting XQuartz..."
#surpress stderr because we don't care if no process was found
killall -m Xquartz 2>/dev/null
echo " ✔️"


echo "You may need to fetch pywal colors in firefox."
echo "If the new discord theme didn't apply run pywal-discord-fix."
