#!/usr/bin/env python3
import tempfile
import subprocess

def open_editor(filename):

    start_vim = [
        'osascript',
        '-e', 'if application "iTerm" is not running then',
        '-e', 'activate application "iTerm"',
        '-e', 'end if',
        '-e', 'tell application "iTerm"',
        '-e', 'set newWindow to (create window with default profile)',
        '-e', f'tell current session of newWindow to write text "nvim -u ~/.config/inkscape/minimal.vim {filename} && exit"',
        '-e', 'set windowID to id of newWindow',
        '-e', 'end tell',
        '-e', 'return windowID'
    ]

    result = subprocess.run(start_vim, capture_output=True, text=True)
    windowID = result.stdout.strip()
        
    adjust_window = f'yabai -m window {windowID} --toggle float && yabai -m window {windowID} --grid 6:7:2:3:3:2'
    subprocess.run(adjust_window, shell=True)

def open_vim():
    f = tempfile.NamedTemporaryFile(mode='w+', delete=False, suffix='.tex')

    f.write('$$')
    f.close()
    open_editor(f.name)

if __name__ == "__main__":
    open_vim()
